In [1]:
import torch
import tensorflow as tf
from torch_geometric.data import Data 
edge_index = torch.tensor([])   
edge_index = torch.tensor([[0,1,1,2],[1,0,2,1]],dtype=torch.long)
x = torch.tensor([[-1],[0],[1]],dtype=torch.float)  
data = Data(x=x,edge_index=edge_index)      

In [2]:
data.x = torch.cat([data.x, torch.tensor([[2]],dtype=torch.float)],0)
# data.x[0] + data.x[3]
data.x

tensor([[-1.],
        [ 0.],
        [ 1.],
        [ 2.]])

In [3]:
data.edge_index.eq(torch.tensor([[0,1]],dtype=torch.long).t().contiguous())

tensor([[1, 0, 0, 0],
        [1, 0, 0, 1]], dtype=torch.uint8)

In [4]:
data.edge_index

tensor([[0, 1, 1, 2],
        [1, 0, 2, 1]])

In [5]:
torch.nonzero(data.edge_index.eq(torch.tensor([[0,1]],dtype=torch.long).t().contiguous()))

tensor([[0, 0],
        [1, 0],
        [1, 3]])

In [6]:
data.edge_index.t()[(data.edge_index.t()[:,0] == 0)&(data.edge_index.t()[:,1] == 1)]

tensor([[0, 1]])

In [7]:
data.edge_index = torch.cat([data.edge_index.t(), torch.tensor([[0,2]],dtype=torch.long)],0).t().contiguous()
data.edge_index

tensor([[0, 1, 1, 2, 0],
        [1, 0, 2, 1, 2]])

In [8]:
data.edge_index.t()[:1]

tensor([[0, 1]])

In [9]:
index = ((data.edge_index.t()[:,0] == 1)&(data.edge_index.t()[:,1] == 0)).nonzero().item()
data.edge_index = torch.cat([data.edge_index.t()[:index],data.edge_index.t()[index+1:]],0).t().contiguous()
data.edge_index

tensor([[0, 1, 2, 0],
        [1, 2, 1, 2]])

In [10]:
((data.edge_index.t()[:,0] == 1)&(data.edge_index.t()[:,1] == 0))|((data.edge_index.t()[:,0] == 1)&(data.edge_index.t()[:,1] == 2))#.nonzero().shape[0]

tensor([0, 1, 0, 0], dtype=torch.uint8)

In [11]:
data.edge_index

tensor([[0, 1, 2, 0],
        [1, 2, 1, 2]])

In [12]:
type(data.edge_index)

torch.Tensor

In [55]:
tar = tf.constant([[0,0,0],[0,1,2]])
fea = tf.constant([[[1.11,2.22],[3.33,4.44],[5.55,6.66]],[[7.77,8.88],[9.99,10.1010],[11.1111,12.1212]]])
N0 = tf.shape(tar)[1]
idx = tf.reshape(tf.range(0,2),(2,1))
idx = tf.tile(idx, (1,N0))
idx = tf.stack((idx, tar), axis=-1)
# idx = tf.gather_nd(fea, idx)
with tf.Session() as sess:
    print(sess.run(idx))
#     print(sess.run(tar))

[[[0 0]
  [0 0]
  [0 0]]

 [[1 0]
  [1 1]
  [1 2]]]
