In [121]:
import torch
import tensorflow as tf
from torch_geometric.data import Data 
edge_index = torch.tensor([])   
edge_index = torch.tensor([[0,1,1,2],[1,0,2,1]],dtype=torch.long)
x = torch.tensor([[-1],[0],[1]],((data.edge_index.t()[:,0] == 1)&(data.edge_index.t()[:,1] == 0)).nonzero()dtype=torch.float)  
data = Data(x=x,edge_index=edge_index)      

In [52]:
data.x = torch.cat([data.x, torch.tensor([[2]],dtype=torch.float)],0)
# data.x[0] + data.x[3]
data.x

tensor([[-1.],
        [ 0.],
        [ 1.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.]])

In [57]:
data.edge_index.eq(torch.tensor([[0,1]],dtype=torch.long).t().contiguous())

tensor([[1, 0, 0, 0],
        [1, 0, 0, 1]], dtype=torch.uint8)

In [58]:
data.edge_index

tensor([[0, 1, 1, 2],
        [1, 0, 2, 1]])

In [61]:
torch.nonzero(data.edge_index.eq(torch.tensor([[0,1]],dtype=torch.long).t().contiguous()))

tensor([[0, 0],
        [1, 0],
        [1, 3]])

In [84]:
data.edge_index.t()[(data.edge_index.t()[:,0] == 0)&(data.edge_index.t()[:,1] == 1)]

tensor([[0, 1]])

In [119]:
data.edge_index = torch.cat([data.edge_index.t(), torch.tensor([[0,2]],dtype=torch.long)],0).t().contiguous()
data.edge_index

tensor([[0, 1, 2, 0, 0],
        [1, 2, 1, 2, 2]])

In [104]:
data.edge_index.t()[:1]

tensor([[0, 1]])

In [122]:
index = ((data.edge_index.t()[:,0] == 1)&(data.edge_index.t()[:,1] == 0)).nonzero().item()
data.edge_index = torch.cat([data.edge_index.t()[:index],data.edge_index.t()[index+1:]],0).t().contiguous()
data.edge_index

tensor([[0, 1, 2],
        [1, 2, 1]])

In [134]:
((data.edge_index.t()[:,0] == 1)&(data.edge_index.t()[:,1] == 0))|((data.edge_index.t()[:,0] == 1)&(data.edge_index.t()[:,1] == 2))#.nonzero().shape[0]

tensor([0, 1, 0], dtype=torch.uint8)

In [136]:
data.edge_index

tensor([[0, 1, 2],
        [1, 2, 1]])

In [138]:
type(data.edge_index)

torch.Tensor